// +build !ignore_autogenerated_openshift

// This file was autogenerated by defaulter-gen. Do not edit it manually!

package v1

import (
	runtime "k8s.io/kubernetes/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&ImageStreamImport{}, func(obj interface{}) { SetObjectDefaults_ImageStreamImport(obj.(*ImageStreamImport)) })
	return nil
}

func SetObjectDefaults_ImageStreamImport(in *ImageStreamImport) {
	for i := range in.Spec.Images {
		a := &in.Spec.Images[i]
		SetDefaults_ImageImportSpec(a)
	}
}
